<a href="https://colab.research.google.com/github/Brenda-moreira25/Aplicacao_final/blob/main/Trabalho_recupera%C3%A7%C3%A3o-IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
# Importa bibliotecas essenciais
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical # Importar to_categorical
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

from sklearn.datasets import load_wine

In [118]:
df = pd.read_csv('WineDataset.csv')
df.head()

Alcohol  Malic Acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline  Wine  
0                          3.92   1065.0     1  
1                          3.40   1050.0     1  
2                          3.17   1185.0     1  
3                          3.45   1480.0     1  
4                          2.93    735.0     1

In [119]:
df.shape

(178, 14)

In [120]:
df.columns = ["Álcool", "Ácido Málico", "Cinzas", "Alcalinidade das cinzas", "Magnésio", "Fenóis totais", "Flavonoides", "Fenóis não flavonoides", "Proantocianidinas", "Intensidade da cor", "Matiz", "OD280/OD315 de vinhos diluídos", "Prolina", "Vinho"]

In [121]:
df.head()

Álcool  Ácido Málico  Cinzas  Alcalinidade das cinzas  Magnésio  \
0   14.23          1.71    2.43                     15.6     127.0   
1   13.20          1.78    2.14                     11.2     100.0   
2   13.16          2.36    2.67                     18.6     101.0   
3   14.37          1.95    2.50                     16.8     113.0   
4   13.24          2.59    2.87                     21.0     118.0   

   Fenóis totais  Flavonoides  Fenóis não flavonoides  Proantocianidinas  \
0           2.80         3.06                    0.28               2.29   
1           2.65         2.76                    0.26               1.28   
2           2.80         3.24                    0.30               2.81   
3           3.85         3.49                    0.24               2.18   
4           2.80         2.69                    0.39               1.82   

   Intensidade da cor  Matiz  OD280/OD315 de vinhos diluídos  Prolina  Vinho  
0                5.64   1.04                            3.92   1065.0      1  
1                4.38   1.05                            3.40   1050.0      1  
2                5.68   1.03                            3.17   1185.0      1  
3                7.80   0.86                            3.45   1480.0      1  
4                4.32   1.04                            2.93    735.0      1

In [122]:
# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalização (obrigatória para redes neurais)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Criar rede neural
model = MLPClassifier(
    hidden_layer_sizes=(16, 8),
    activation='relu',
    solver='adam',
    max_iter=1000
)

# Treinar
model.fit(X_train, y_train)

# Prever
pred = model.predict(X_test)

print(pred)


[1 1 3 1 2 1 2 3 2 3 1 3 1 2 1 2 2 2 1 2 1 2 2 3 3 3 2 2 2 1 1 2 3 1 1 1]


In [123]:
print("Valores únicos e suas contagens em y_train:")
print(y_train.value_counts())
print("\nValores únicos e suas contagens em y_test:")
print(y_test.value_counts())

Valores únicos e suas contagens em y_train:
Vinho
2    57
1    45
3    40
Name: count, dtype: int64

Valores únicos e suas contagens em y_test:
Vinho
1    14
2    14
3     8
Name: count, dtype: int64


In [124]:
base = load_wine()

previsores = base.data # dados de parametros
classes = base.target #dado que vamos prever

classes # cada número é um tipo de classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [125]:
classe_dummy = to_categorical(classes) # converte em número
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [126]:
X_treinamento, x_teste, y_treinamento, y_teste = train_test_split(
    previsores, classe_dummy, #utilizo já convertida
    test_size=0.3,
    random_state=0)

In [127]:
modelo = Sequential()

In [128]:
#criar camadas
modelo.add(Dense(units=5, input_dim=4))
#Criei 5 neuronios e 4 variaveis de entradas// quanto mais neoronios mais as informações vão se cruzar. mas não significa que será mais assertivo

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [129]:
#mais uma camada com 4 neurônios
modelo.add(Dense(units=4))

In [130]:
modelo.summary()
#mostra detalhes da arquitetura (nº de camadas e parâmetros treinaveis)
#param = (nº de entradas x nº de neuronios) + nº de neuronios

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4)              │            24 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 49 (196.00 B)

 Trainable params: 49 (196.00 B)

 Non-trainable params: 0 (0.00 B)