<a href="https://colab.research.google.com/github/Brenda-moreira25/Aplicacao_final/blob/main/Trabalho_recupera%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [271]:
# Importa bibliotecas essenciais
import pandas as pd

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

import tensorflow as tf
from tensorflow import keras

from sklearn.preprocessing import LabelEncoder

In [272]:
df = pd.read_csv('13100166.csv')

# Renomear a coluna 'Age group' para 'Age_group'
df = df.rename(columns={'Age group': 'Age_group'})

# Visualizar as primeiras linhas
df.head()

REF_DATE     GEO  DGUID       Age_group  Teen pregnancy outcomes  \
0      1998  Canada    NaN  15 to 19 years  Total, teen pregnancies   
1      1998  Canada    NaN  15 to 19 years  Total, teen pregnancies   
2      1998  Canada    NaN  15 to 19 years              Live births   
3      1998  Canada    NaN  15 to 19 years              Live births   
4      1998  Canada    NaN  15 to 19 years        Induced abortions   

          Characteristics                      UOM  UOM_ID SCALAR_FACTOR  \
0        Number of events                   Number     223        units    
1  Rate per 1,000 females  Rates per 1,000 females     266        units    
2        Number of events                   Number     223        units    
3  Rate per 1,000 females  Rates per 1,000 females     266        units    
4        Number of events                   Number     223        units    

   SCALAR_ID    VECTOR COORDINATE    VALUE  STATUS SYMBOL TERMINATED  DECIMALS  
0          0  v4384837    1.1.1.1  41588.0     NaN    NaN        NaN         0  
1          0  v4384838    1.1.1.2     41.7     NaN    NaN        NaN         1  
2          0  v4384839    1.1.2.1  19721.0     NaN    NaN        NaN         0  
3          0  v4384840    1.1.2.2     19.8     NaN    NaN        NaN         1  
4          0  v4384841    1.1.3.1  20859.0     NaN    NaN        NaN         0

In [273]:
df.shape

(960, 17)

In [274]:
df.columns = ["ano_pesq", "cidade_pesq", "raça", "faixa_idade", "dados_gestaçao", "media_gesta_tt", "multi_gestações", "media_gesta_faixa_etaria", "quant_fetos", "mae_solteira", "codigo_carteira_gestante", "cordenadas", "peso", "parceiro_presente", "id_parceiro", "usado_presenv", "interrompeu_gestação"]

In [275]:
df.head()

ano_pesq cidade_pesq  raça     faixa_idade           dados_gestaçao  \
0      1998      Canada   NaN  15 to 19 years  Total, teen pregnancies   
1      1998      Canada   NaN  15 to 19 years  Total, teen pregnancies   
2      1998      Canada   NaN  15 to 19 years              Live births   
3      1998      Canada   NaN  15 to 19 years              Live births   
4      1998      Canada   NaN  15 to 19 years        Induced abortions   

           media_gesta_tt          multi_gestações  media_gesta_faixa_etaria  \
0        Number of events                   Number                       223   
1  Rate per 1,000 females  Rates per 1,000 females                       266   
2        Number of events                   Number                       223   
3  Rate per 1,000 females  Rates per 1,000 females                       266   
4        Number of events                   Number                       223   

  quant_fetos  mae_solteira codigo_carteira_gestante cordenadas     peso  \
0      units              0                 v4384837    1.1.1.1  41588.0   
1      units              0                 v4384838    1.1.1.2     41.7   
2      units              0                 v4384839    1.1.2.1  19721.0   
3      units              0                 v4384840    1.1.2.2     19.8   
4      units              0                 v4384841    1.1.3.1  20859.0   

   parceiro_presente id_parceiro usado_presenv  interrompeu_gestação  
0                NaN         NaN           NaN                     0  
1                NaN         NaN           NaN                     1  
2                NaN         NaN           NaN                     0  
3                NaN         NaN           NaN                     1  
4                NaN         NaN           NaN                     0

In [276]:

#Separar previsores (X) e resto (y)
target_column = 'interrompeu_gestação' # Mantenha o nome da sua coluna target
X = df.drop(target_column, axis=1)
y = df[target_column]

# Ele detecta automaticamente colunas do tipo 'object' (string) e as converte.
X_encoded = pd.get_dummies(X, drop_first=True)

# Visualizar as primeiras linhas após a codificação (para confirmar a mudança)
print("Features após One-Hot Encoding:")
print(X_encoded.head())

#

Features após One-Hot Encoding:
   ano_pesq  raça  media_gesta_faixa_etaria  mae_solteira     peso  \
0      1998   NaN                       223             0  41588.0   
1      1998   NaN                       266             0     41.7   
2      1998   NaN                       223             0  19721.0   
3      1998   NaN                       266             0     19.8   
4      1998   NaN                       223             0  20859.0   

   parceiro_presente  cidade_pesq_British Columbia  cidade_pesq_Canada  \
0                NaN                         False                True   
1                NaN                         False                True   
2                NaN                         False                True   
3                NaN                         False                True   
4                NaN                         False                True   

   cidade_pesq_Manitoba  cidade_pesq_New Brunswick  ...  cordenadas_9.2.4.1  \
0                 False

In [277]:
target_column = 'interrompeu_gestação' # coluna a ser analisada
X = df.drop(target_column, axis=1) # resto
y = df[target_column] # previsores

In [278]:
# 70% para treino, 30% para teste
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, random_state=42
)
label_encoder = LabelEncoder()


y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)


y_train_categorical = to_categorical(y_train_encoded)
y_test_categorical = to_categorical(y_test_encoded)

num_classes = len(label_encoder.classes_)

print(f"Number of classes: {num_classes}")
print(f"y_train_categorical shape: {y_train_categorical.shape}")
print(f"y_test_categorical shape: {y_test_categorical.shape}")

Number of classes: 2
y_train_categorical shape: (672, 2)
y_test_categorical shape: (288, 2)


In [279]:
# Fazer previsões no conjunto de teste
predictions = model.predict(X_test)

# Visualizar as 10 primeiras previsões
print("\nPrimeiras 10 previsões:")
print(predictions[:10])

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 

Primeiras 10 previsões:
[[0.6181977  0.1518085  0.22999373]
 [0.45377275 0.27969247 0.2665348 ]
 [0.5606444  0.23547024 0.20388533]
 [0.33847263 0.47454572 0.18698159]
 [0.16910936 0.09665231 0.7342383 ]
 [0.5653963  0.23258178 0.20202182]
 [0.7943503  0.13482715 0.07082249]
 [0.3967752  0.29361466 0.30961007]
 [0.9526859  0.02659368 0.02072044]
 [0.72217524 0.19394755 0.08387712]]


In [280]:
# Número de features de entrada (dimensão da camada de entrada)
input_dim = X_train.shape[1]

# Definir o modelo Sequencial
model = keras.Sequential([
    # Camada de Entrada e Primeira Camada Oculta (Dense)
    keras.layers.Dense(64, activation='relu', input_shape=(input_dim,)),
    # Camada Oculta Adicional
    keras.layers.Dense(32, activation='relu'),
    # Camada de Saída para Classificação Multiclasse
    keras.layers.Dense(num_classes, activation='softmax') # 'num_classes' é o número de categorias
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [281]:
#criar camadas
modelo.add(Dense(units=6, input_dim=4))
#Criei 6 neuronios e 4 variaveis de entradas// quanto mais neoronios mais as informações vão se cruzar. mas não significa que será mais assertivo

In [282]:
#mais uma camada com 4 neurônios
modelo.add(Dense(units=4))

In [283]:
modelo.add(Dense(units=3))
#terceira camada com 3 neurônios
#Escolhi 3 pois tenho três possibilidades de respostas

In [284]:
modelo = Sequential() # Initialize the Sequential model
modelo.summary()
#mostra detalhes da arquitetura (nº de camadas e parâmetros treinaveis)
#param = (nº de entradas x nº de neuronios) + nº de neuronios

Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [285]:
modelo.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
#otimizador vai modificar e regular os pesos das entradas
#loss: função para monitorar a perda de dados
#acurracy: monitora a precisão durante o treinamento